# Generated by Django 4.1.3 on 2022-12-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_is_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="nombre",
            field=models.CharField(blank=True, max_length=30, verbose_name="Nombre"),
        ),
    ]
