# Generated by Django 4.1.3 on 2022-12-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "num_reserva",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Reserva nº"
                    ),
                ),
            ],
            options={
                "verbose_name": "Reserva",
                "verbose_name_plural": "Reservas",
                "ordering": ["num_reserva"],
            },
        ),
    ]
