# Generated by Django 4.1.3 on 2022-12-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "num_reserva",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Reserva nº"
                    ),
                ),
                (
                    "camas_reservadas",
                    models.IntegerField(
                        default=1, verbose_name="Nº de camas reservadas"
                    ),
                ),
                (
                    "fecha_reserva_entrada",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de entrada"
                    ),
                ),
                (
                    "pago_confirmado",
                    models.BooleanField(default=False, verbose_name="Pago confirmado"),
                ),
                (
                    "documentos",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="media/",
                        verbose_name="Documentación",
                    ),
                ),
                (
                    "camas_disponibles",
                    models.IntegerField(
                        blank=True,
                        default=7,
                        editable=False,
                        null=True,
                        verbose_name="Camas disponibles",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reserva",
                "verbose_name_plural": "Reservas",
                "ordering": ["num_reserva"],
            },
        ),
    ]
