# Generated by Django 4.1.3 on 2022-12-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reserva",
            name="camas_reservadas",
            field=models.IntegerField(default=1, verbose_name="Camas reservadas"),
        ),
    ]
