# Generated by Django 4.1.3 on 2022-12-29 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservas", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelTable(name="reserva", table="reservas_reserva",),
    ]
