# Generated by Django 4.1.3 on 2022-12-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservas", "0002_reserva_camas_reservadas"),
    ]

    operations = [
        migrations.AddField(
            model_name="reserva",
            name="fecha_reserva_entrada",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de entrada"
            ),
        ),
    ]
