# Generated by Django 4.1.3 on 2022-12-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservas", "0003_reserva_fecha_reserva_entrada"),
    ]

    operations = [
        migrations.AddField(
            model_name="reserva",
            name="pago_confirmado",
            field=models.BooleanField(default=False, verbose_name="Pago confirmado"),
        ),
    ]
