# Generated by Django 4.1.3 on 2022-12-29 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservas", "0003_alter_reserva_table"),
    ]

    operations = [
        migrations.AlterModelTable(name="reserva", table="reserva",),
    ]
