# Generated by Django 4.1.3 on 2022-12-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservas", "0007_reserva_mail_usuario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reserva",
            name="num_reserva",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="Reserva"
            ),
        ),
    ]
